config/routes.rb
JsRu::Application.routes.draw do
  resources :tags

  resources :questions do
    get :solve, on: :member
    resources :answers
  end

  resources :tags do
    get  :subscribe, on: :member
    member do
      post :create
    end
  end

  resources :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates_presence_of :text
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :views
  has_and_belongs_to_many :tags

  validates_presence_of :title, :text, :tags

  paginates_per 10

  scope :with_counted_answers, -> {
    joins('LEFT OUTER JOIN answers ON answers.question_id = questions.id')
    .group('questions.id')
  }

  scope :without_answers, -> {
    with_counted_answers
    .having('count(answers.id) = 0')
  }

  scope :hot, -> {
    with_counted_answers
    .having('count(answers.id) > 0')
    .where("answers.created_at > ?", 1.month.ago)
    # TODO add subscriptions counting
  }

  def self.search(search)
   if search
     Question.try(search.to_sym)
    else
      Question.order('created_at desc')
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :questions
  has_many :subscriptions

  validates :name, uniqueness: true

  def subscibe_unsubscribe(user)
    subscription = user.subscribed_to?(self)
    case subscription
      when nil then Subscription.create(user: user, tag: self)
      else subscription.destroy
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :views
  has_many :subscriptions

  def already_viewed?(question)
    # add condition  || self == question.user
    true if self.views.where(question: question).present?
  end

  def subscribed_to?(tag)
    Subscription.where(user: self, tag: tag).first
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :find_question, only: [:create, :update]


  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question

    if @answer.save
      redirect_to @question
    else
      flash[:error] = t action_name, scope: [:messages, :answers, :errors]
      redirect_to @question
    end
  end

  def update
    if @answer.update(answer_params)
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to @question
    else
      flash[:error] = t action_name, scope: [:messages, :answers, :errors]
      redirect_to @question
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
    redirect_to answers_url
  end

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def find_question
      @question = Question.find(params[:question_id])
    end

    def answer_params
      params.require(:answer).permit(:text, :rating, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :current_user

# stub for now
  def current_user
    @current_user ||= User.last
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :solve]
  before_action :create_tags_unless_exist, only: [:create]

  def index
    @questions = Question.search(params[:search]).page(params[:page])
  end

  def show
   current_user.views.create(question: @question) unless current_user.already_viewed?(@question)
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to questions_path
    else
      render action: 'new'
    end
  end

  def update
    if @question.update(question_params)
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to @question
    else
      render action: 'edit'
    end
  end

  def destroy
    @question.destroy

    redirect_to questions_url
  end

  def create_tags_unless_exist
   if params[:tags_names]
      names = params[:tags_names].split(',')
      names.each { |n| Tag.create(name: n) unless Tag.find_by_name(n).present? }
    end
  end

  def solve
    @question.update(question_params)
    redirect_to @question
  end

  private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :text, :rating, :user_id, :tags_names, :is_solved, tag_ids: [])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy, :subscribe]

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to tags_path
    else
      render action: 'new'
    end
  end

  def update
    if @tag.update(tag_params)
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to @tags
    else
      render action: 'edit'
    end
  end

  def destroy
    @tag.destroy

    flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
    redirect_to tags_url
  end

  def subscribe
    @tag.subscibe_unsubscribe(@current_user)

    redirect_to tags_path
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to users_path
    else
      render action: 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
      redirect_to @users
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy

    flash[:success] = t action_name, scope: [:messages, controller_name.to_sym]
    redirect_to users_url
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = sort_direction || "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def subscribe_btn(tag)
    options = case @current_user.subscribed_to?(tag)
    when nil then {text: 'Подписаться', klass: 'subscribe'}
    else {text: 'Подписан', klass: 'subscribed'}
    end

     link_to options[:text], subscribe_tag_path(tag), method: :get, class: "btn sbscrn pull-right #{options[:klass]}"
  end
end

app/views/answers/_answer.html.erb
<span ><%= answer.text %></span>
<hr class="divider">

app/views/answers/_form.html.erb
<%= render 'shared/flash', flash: flash %>

<%= fa_icon 'pencil-square-o ' %> Написать ответ:
<%= form_for([@question, @question.answers.build]) do |f| %>
  <div class="field">
    <%= f.text_area :text, rows: 6, maxlength: 400 %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<ul class="nav nav-pills" role="navigation">
  <li><a href="">Обучение</a></li>
  <li><a href="">Блоги</a></li>
  <li><%= link_to '? Вопрос / Ответ', questions_path%></li>
  <li><a href="">Справочник</a></li>
  <li><a href="">События</a></li>
  <li><a href="">Работа</a></li>
  <li><a href="">Песочница</a></li>
  <li><a href="">Чат</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsRu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-static-top masthead navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= render 'layouts/header' %>
      </div>
    </div>
  </div>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_aside.html.erb
<ul class="nav nav-tabs nav-stacked pull-right">
  <li><%= link_to 'Задать вопрос', new_question_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Вопросы<b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Все', questions_path%></li>
      <li><a href="#">Моя лента</a></li>
      <li><a href="#">Подписан</a></li>
      <li><a href="#">Мои</a></li>
    </ul>
  </li>
  <li><%= link_to 'Теги', tags_path%></li>
  <li><%= link_to 'Пользователи', users_path%></li>
</ul>

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= render 'aside' %>

<%= form_for @question  do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text, rows: 6, class: 'span8', maxlength: 400 %>
  </div>

  <div class="field">
    <%= f.label :tag_ids %>
    <%= f.collection_select :tag_ids, Tag.all, :id, :name, { include_hidden: false },
    { multiple: true, class: 'chzn-select',data: { placeholder: 'Выбери теги'} } %>
  </div>


  <%= hidden_field_tag :tags_names %>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>

<% end %>

<script type="text/javascript">
  $('#question_tag_ids_chosen').find('input').on('keyup', function(e) {
    if (e.which == 13 && $('#question_tag_ids_chosen').find('input').val() != '') {
      names = []
      $('.search-choice').each(function( ) {
        names.push($( this ).text());
      });
      $('#tags_names').text(names);
      console.log($('#tags_names').text());
    }
  });
</script>

app/views/questions/_question.html.erb
<div class="question_view">
  <h4><%= link_to question.title, question  %></h4>
  <span class="pull-right" id="rating"><%= question.rating %></span>
  <% if question.is_solved %>
    <span class="badge badge-sml">Решено</span>
  <% end %>
  <%= fa_icon 'comment' %> <%= question.answers.count %>
  <%= fa_icon 'eye' %> <%= question.views.count %>
  <%= fa_icon 'user' %> <%= question.user.name %>
  <%= fa_icon 'clock-o' %> <%= distance_of_time_in_words(Time.now, question.created_at) %> назад</br></br>
  <% if action_name != 'index' %>
    <div><%= question.text %></div></br>
  <% end %>
  <% if question.tags.present? %>
    <% question.tags.each do |t| %>
      <span class="tag"><%= t.name %></span>
    <% end %>
  <% end %>

  <% if action_name != 'index' && @current_user == @question.user %>
    <% unless @question.is_solved %>
      <%= form_for question, url: solve_question_path, method: :get, html: { class: 'autosubmit-form' } do |f| %>
        <div class="control-group">
          <%= f.check_box :is_solved %>
         <label class="btn btn-default pull-right" for="question_is_solved">Решено</label>
        </div>
      <% end %>
    <% end %>
    <span class="pull-right"><%= link_to 'Редактировать', edit_question_path(@question) %></span>
  <% end %>
  <hr class="divider">
</div>

app/views/questions/edit.html.erb
<legend>Редактировать вопрос</legend>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="question-sort pull-right" >
  <div class="btn-group" >
    <%= link_to 'Новые', questions_path, class: 'btn btn-default' %>
    <%= link_to 'Горячие', questions_path(search: :hot), class: 'btn btn-default' %>
    <%= link_to 'Без ответов', questions_path(search: :without_answers), class: 'btn btn-default' %>
  </div>
</div>

<legend>Вопросы</legend>
<%= render 'shared/flash', flash: flash %>
<%= render 'aside' %>
<div class="questions_list">
  <%= render @questions %>
</div>

<%= paginate @questions %>

app/views/questions/new.html.erb
<legend>Задать вопрос</legend>

<%= render 'form' %>

app/views/questions/show.html.erb
<%= render 'aside' %>

<%= render @question %>

<span><%= fa_icon 'comment' %> Ответы(<%= @question.answers.count %>)</span>
<span>написать <%= fa_icon 'long-arrow-down' %></span>
<hr class="divider">

<% if @question.answers.present? %>
  <%= render @question.answers %>
<% end %>

<%= render 'answers/form'%>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-block alert-error">
    <% object.errors.each do |field, msg| %>
      <li><%= msg %>.</li>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/tags/index.html.erb
<legend>Теги</legend>

<%= render 'shared/flash' %>
<%= render 'questions/aside' %>
<div class="tags_list">
  <% @tags.each do |tag| %>
    <div>
      <span id="tag_name"><%= tag.name %></span></br>
      Вопросов:<span class="red-text"><%= tag.questions.count %></span>
      Подписчиков:<span class="red-text"><%= tag.subscriptions.count %></span>
      <%= subscribe_btn(tag) %>
    </div>
    <hr class="divider">
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/flash', flash: flash %>
<%= render 'shared/errors', object: @user %>

<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<legend>Пользователи</legend>
<ol>
  <% @users.each do |user| %>
    <li>
      <%= image_tag("image.jpeg") %>
      <%= user.name %></br>
      Ответов: <%= user.answers.count %>
      Воспросов: <%= user.questions.count %>
    </li>
    <hr class="divider">
  <% end %>
</ol>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>